vich_uploader:
    db_driver: orm

    mappings:
        profile_picture:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/assets/img/profile_picture'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true